package:
  name: python-pygaze
  version: "0.6.0a14"

source:
  fn: python-pygaze-0.6.0a14.tar.gz
  url: https://pypi.python.org/packages/c2/d2/6dadd2744490b993ed412b7212a83bccf362db6650eb27c9c6ee8ef3408f/python-pygaze-0.6.0a14.tar.gz
  md5: 18b218bbf7eec339a40de5a67f6d01ec

build:
  noarch_python: True
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pygaze
    - pygaze._display
    - pygaze._eyetracker
    - pygaze._joystick
    - pygaze._keyboard
    - pygaze._logfile
    - pygaze._misc
    - pygaze._mouse
    - pygaze._screen
    - pygaze._sound
    - pygaze._time
    - pygaze.plugins

about:
  home: http://www.pygaze.org/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'A Python library for eye tracking'

