package:
  name: python-opensesame
  version: "3.1.0.a30"

source:
  fn: python-opensesame-3.1.0a30.tar.gz
  url: https://pypi.python.org/packages/source/p/python-opensesame/python-opensesame-3.1.0a30.tar.gz
  md5: 83b09885b177d7e9c9fb087ff19bdc6e

build:
  noarch_python: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - webcolors
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom

  run:
    - python
    - pyqt
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - billiard      # [osx and py2k]

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'
