package:
  name: python-fileinspector
  version: "1.0.1"

source:
  git_rev: v1.0.1
  git_url: https://github.com/dschreij/fileinspector.git

build:
  noarch_python: True
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - fileinspector

about:
  home: https://github.com/dschreij/fileinspector
  license: GNU General Public License v3 (GPLv3)
  summary: 'A module to determine file mimetypes'