{% set name = "opensesame-extension-osf" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/dschreij/{{ name }}.git

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - setuptools
    - python-opensesame
    - python-qosf

  run:
    - python
    - python-opensesame
    - python-qosf

about:
  home: https://github.com/dschreij/{{ name }}
  license: Apache Software License
  summary: 'OpenSesame OSF extension'
