{% set name = "opensesame-extension-osf" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/dschreij/{{ name }}.git

build:
  noarch_python: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-opensesame
    - python-qosf

  run:
    - python
    - python-opensesame
    - python-qosf

about:
  home: https://github.com/dschreij/{{ name }}
  license: Apache Software License
  summary: 'OpenSesame OSF extension'
