{% set name = "python-opensesame" %}
{% set version = "3.2.7" %}
{% set sha256 = "49a486ad984c7e62ea05e830fff47ac19021f75f3e43d05b0600d8933e71dc87" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/ce/43/f713f9b41e25653cd6fed6f25074d56f25ce6a698cd26735db64a75d1386/{{ name }}-{{ version}}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - webcolors
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications

  run:
    - python
    - pyqt
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes

test:
  imports:
    - libopensesame
    - libqtopensesame
    - openexp

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

# If the app key is present, the package will be an app, meaning it will
# appear in the Anaconda launcher.
app:
  # The command that is called to launch the app
  entry: opensesame
  # Icon file contained in the recipe
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
  # If own_environment is true, installing the app through the launcher
  # will install into its own environment. The default is false.
  # own_environment: true

