{% set name = "python-opensesame" %}
{% set version = "3.2.8" %}
{% set sha256 = "51ceceb114b3e2f189ec7e17e6ddd305ec5e3e3f576b7ef8072e91f4ca64317f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/e0/c7/af02f00246f9c2f1b0c3497c8c2b8f6942cd4cd58cdf931061c94afbaa71/{{ name }}-{{ version}}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - webcolors
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications

  run:
    - python
    - pyqt
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes

test:
  imports:
    - libopensesame
    - libqtopensesame
    - openexp

about:
  home: https://github.com/smathot/OpenSesame
  license: GPLv3
  summary: 'Graphical experiment builder for the social sciences'

# If the app key is present, the package will be an app, meaning it will
# appear in the Anaconda launcher.
app:
  # The command that is called to launch the app
  entry: opensesame
  # Icon file contained in the recipe
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
  # If own_environment is true, installing the app through the launcher
  # will install into its own environment. The default is false.
  # own_environment: true

