package:
  name: python-qprogedit
  version: "4.0.0a2"

source:
  git_rev: prerelease/4.0.0a2
  git_url: https://github.com/smathot/QProgEdit.git

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-pseudorandom = python-pseudorandom:main
    #
    # Would create an entry point called python-pseudorandom that calls python-pseudorandom.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - qtpy
    - qscintilla2

  run:
    - python
    - qtpy
    - qscintilla2

test:
  # Python imports
  imports:
    - QProgEdit

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/smathot/QProgEdit
  license: GNU General Public License v3 (GPLv3)
  license_file: COPYING
  summary: 'QProgEdit is a PyQt4 widget that implements a full-featured text editor component'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
