package:
  name: billiard
  version: "3.3.0.23"

source:
  fn: billiard-3.3.0.23.tar.gz
  url: https://pypi.python.org/packages/64/a6/d7b6fb7bd0a4680a41f1d4b27061c7b768c673070ba8ac116f865de4e7ca/billiard-3.3.0.23.tar.gz
  md5: 6ee416e1e7c8d8164ce29d7377cca6a4

build:
  noarch_python: True
  # preserve_egg_dir: True
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - billiard
    - billiard.dummy
    - billiard.py2
    - billiard.tests
    - funtests

  requires:
    - mock
    - nose >=1.3.4
    - setuptools >=17.1
    - unittest2 >=0.4.0
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/celery/billiard
  license: BSD License
  summary: 'Python multiprocessing fork with improvements and bugfixes'