{% set name = "python-qprogedit" %}
{% set version = "4.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  git_rev: release/{{ version }}
  git_url: https://github.com/smathot/QProgEdit.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  build:
    - python
    - setuptools
    - qtpy
    - qscintilla2
    - pyqt

  run:
    - python
    - qtpy
    - pyflakes
    - qscintilla2
    - pyqt

test:
  # Python imports
  imports:
    - QProgEdit

about:
  home: https://github.com/smathot/QProgEdit
  license: GNU General Public License v3 (GPLv3)
  license_file: COPYING
  summary: 'QProgEdit is a PyQt widget that implements a full-featured text editor component'
