package:
  name: python-qprogedit
  version: "4.0.3"

source:
  git_rev: release/4.0.3
  git_url: https://github.com/smathot/QProgEdit.git

build:
  noarch_python: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - qtpy
    - qscintilla2

  run:
    - python
    - qtpy
    - pyflakes
    - qscintilla2

test:
  # Python imports
  imports:
    - QProgEdit

about:
  home: https://github.com/smathot/QProgEdit
  license: GNU General Public License v3 (GPLv3)
  license_file: COPYING
  summary: 'QProgEdit is a PyQt4 widget that implements a full-featured text editor component'
