package:
  name: qscintilla2
  version: 2.9.2

source:
  fn:   QScintilla-gpl-2.9.2.tar.gz                                                                             [unix]
  url:  https://sourceforge.net/projects/pyqt/files/QScintilla2/QScintilla-2.9.2/QScintilla_gpl-2.9.2.tar.gz  [unix]
  md5:  db260651a5e086cc4eee6417172e27e8                                                                        [unix]
  fn:   QScintilla-gpl-2.9.2.zip                                                                                [win]
  url:  https://sourceforge.net/projects/pyqt/files/QScintilla2/QScintilla-2.9.2/QScintilla_gpl-2.9.2.zip     [win]
  md5:  956928f5b939b11f4bb8f62fe79c8dbc                                                                        [win]

requirements:
  build:
    - python     
    - sip         >=4.16.4
    - qt          >=4.8.7
    - pyqt        >=4.11.4 

  run:
    - python
    - sip         >=4.16.4
    - qt          >=4.8.7
    - pyqt        >=4.11.4

build:
  features:
    - vc9           [win and py27]
    - vc10          [win and py34]
    - vc14          [win and py35]
  script_env:
    - LOCALAPPDATA  [win and py27]

test:
  imports:
    - PyQt4.Qsci

about:
    home: https://www.riverbankcomputing.com/software/qscintilla/intro
    summary: "Qscintilla2 editor for PyQt package"
    license: GPLv3
