package:
  name: requests-oauthlib
  version: "0.6.1"

source:
  fn: requests-oauthlib-0.6.1.tar.gz
  url: https://pypi.python.org/packages/f9/98/a1aaae4bbcde0e98d6d853c4f08bd52f20b0005cefb881679bcdf7ea7a00/requests-oauthlib-0.6.1.tar.gz
  md5: f159bc7675ebe6a2d76798f4c00c5bf8

build:
  noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - oauthlib >=0.6.2
    - requests >=2.0.0

  run:
    - python
    - oauthlib >=0.6.2
    - requests >=2.0.0

test:
  # Python imports
  imports:
    - requests_oauthlib
    - requests_oauthlib.compliance_fixes

  requires:
    - mock
    - requests-mock
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/requests/requests-oauthlib
  license: BSD License
  summary: 'OAuthlib authentication support for Requests.'