package:
  name: python-bidi
  version: "0.4.0"

source:
  fn: python-bidi-0.4.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-bidi/python-bidi-0.4.0.tar.gz
  md5: d8315e421f06eb837556fa4ef4e726e0
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-bidi = python-bidi:main
    #
    # Would create an entry point called python-bidi that calls python-bidi.main()

    - pybidi = bidi:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - bidi

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pybidi --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/MeirKriheli/python-bidi
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Pure python implementation of the BiDi layout algorithm'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
