# vi: sw=2 ts=2 sts=2 expandtab

package:
  name: pygame
  version: 1.9.2a0

source:                                       [unix]
  hg_url: https://bitbucket.org/pygame/pygame [unix]
  hg_tag: cdb0ba7                             [unix]
  
  patches:                                    [unix]
    - test_py35.patch                 [py3k and unix]    

build:
  number: 0

# NOTE: A bunch of OS-specific build requirements are not listed here.
#       See build.sh, which attempts to install (or at least check) for those.
requirements:
  build:
    - setuptools
    - python
  run:
    - python
    - numpy

test: 
  imports:
    - pygame
    - pygame.locals

  commands:                [unix]
    - cd $SRC_DIR          [unix]
    - python setup.py test [unix] 
  
about:
  home: https://pygame.org
  license: LGPL 
